version: '3'

services:

  backend:
    build: backend/
    networks:
      - database
    restart: on-failure
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - 8080:8080

  # frontend:
  #   build: frontend/
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - frontend/.env

  db:
    image: "postgres:alpine"
    networks:
      - database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: on-failure

networks:
  database:
